.travis.yml

chore: add GITHUB_TOKEN for travis

---

README.md

See README.md file for changes.

docs: add cozy-collect documentation

---

.vscode/launch.json
README.md
googleHelper.js
package.json
src/google.js
src/index.js
src/transpiler.js
yarn.lock

I forget to clean up the `index.js` code.
And the `curl` that configures the server was missing the `token_endpoint`.
See #14 for more details.

fix: get access_token from the server's stack

---

CODEOWNERS

chore: add owner for JS files

---

.prettierignore
googleHelper.js
package.json
src/__snapshots__/transpiler.spec.js.snap
src/google.js
src/index.js
src/transpiler.js
webpack.config.js
yarn.lock

_To anticipate this renovate's Pull Request (https://github.com/konnectors/cozy-konnector-google/pull/13), I rebased this dev branch on it. But it appears that renovate works too fast for me, so I had to close the #13 PR. But I don't want to lose time rebasing this PR without the 2 commits added by #13, so they are included with my work._
This PR add information from google user's account to solidify the link with the `io.cozy.contacts`. So I added some `metadata` and an account's email by using a second API.
I was asking myself if it could be a good idea to keep the `resourceName` string as the unique reference and so using something like `resourceName = `${accountEmail}:${resourceName}`. What do you think about?

feat: Add information to solidify the link

---

README.md
googleHelper.js
package.json
yarn.lock

A few updates to the docs and processes used to develop this konnector.

Enhanced documentation

---

manifest.konnector
src/constants.js
src/cozy.js
src/getCozyToGoogleStrategy.js
src/getCozyToGoogleStrategy.spec.js
src/google.js
src/index.js
src/synchronizeContacts.js
src/synchronizeContacts.spec.js

Get or create io.cozy.contacts.accounts and use its id in cozyMetadata

feat: use io.cozy.contacts.accounts

---

manifest.konnector

The konnector has to be launched every day.

feat: Run daily

---

.gitignore
src/__snapshots__/synchronizeContacts.spec.js.snap
src/constants.js
src/cozy.js
src/getCozyMetadata.js
src/getCozyToGoogleStrategy.spec.js
src/getGoogleToCozyStrategy.spec.js
src/index.js

Adds the missing metadata on `io.cozy.contacts` and `io.cozy.contacts.accounts`.

Add missing metadata

---

manifest.konnector

Change "similarly" by "same" in english long description

chore: Update english long description

---

src/__mocks__/googleapis.js
src/__snapshots__/synchronizeContacts.spec.js.snap
src/google.js
src/google.spec.js
src/mergeContact.js
src/mergeContact.spec.js
src/synchronizeContacts.js
src/synchronizeContacts.spec.js
src/transpiler.js

Sync edited contacts on cozy to google

---

src/index.js

Fixes the following:
- Sometimes, Google API responds with an error containing : _"Request requires one of the following scopes"_ instead of _"Request had insufficient authentication scopes."_
- When an error is encountered while asking for a refresh token, we have to throw a `USER_ACTION_NEEDED_OAUTH_OUTDATED` error to force user to re-accept OAuth

fix: Throw OAUTH_OUTDATED if we encounter an error during token refresh

---

src/__snapshots__/synchronizeContacts.spec.js.snap
src/cozy.js
src/index.js
src/mergeContact.js
src/synchronizeContacts.js
src/synchronizeContacts.spec.js
src/transpiler.spec.js

Remaining:
- use cozy-client to write `cozyMetadata` while saving (waiting for : https://github.com/cozy/cozy-client/pull/365 )
Meanwhile, we can merge this.

Synchronize contacts that have been edited on google to cozy

---

src/__snapshots__/synchronizeContacts.spec.js.snap
src/index.js
src/synchronizeContacts.js
src/synchronizeContacts.spec.js

Delete from cozy the contacts that have been deleted in google

Sync: Delete google to cozy

---

src/__snapshots__/synchronizeContacts.spec.js.snap
src/synchronizeContacts.js

Add / update `contact.relationships.accounts` when we add or update a contact in cozy

Update accounts relationship

---

src/__mocks__/googleapis.js
src/__snapshots__/synchronizeContacts.spec.js.snap
src/__snapshots__/transpiler.spec.js.snap
src/google.js
src/index.js
src/synchronizeContacts.js
src/synchronizeContacts.spec.js
src/transpiler.js

When a contact has been edited on cozy and on google since last sync, update cozy contact to use values that come from google contact (all data on cozy contact is lost)

Don't fail when a contact has been edited both on cozy and google since last sync

---

src/CozyUtils.js
src/CozyUtils.spec.js
src/GoogleUtils.js
src/GoogleUtils.spec.js
src/index.js
src/synchronizeContacts.spec.js

Change cozy utils and google utils in proper js classes

Refactor: Proper classes for cozy utils and google utils

---

src/CozyUtils.spec.js

Tests were broken since cozy-client update

test: Fix CozyUtils tests

---

src/CozyUtils.js
src/CozyUtils.spec.js

When we can't find a `io.cozy.contacts.account` with the correct `sourceAccountId`, we try to find one with the same email.

feat: Avoid contact duplication on reconnection

---

src/index.js

It seems that the previous fix introduce an unexpected behaviour. This PR aims to go back to the `1.3.0` behaviour when Google responds by `No refresh token is set.` or `Invalid Credentials` : use the refresh token. 
We just log an error if the `else` is reached.

fix: Don't throw OAUTH_OUTDATED on Invalid credentials

---

src/CozyUtils.js
src/CozyUtils.spec.js
src/constants.js
src/index.js

Set `accountName` so that it is displayed in `cozy-home`

feat: Set auth.accountName on io.cozy.accounts

---

src/onDeleteAccount.js

`onDeleteAccount`: if there is no contact account, don't fail and do nothing.

fix(onDeleteAccount): don't fail if there is no contact account

---

package.json
yarn.lock

Revert  `cozy-jobs-cli` and `cozy-konnector-libs` updates

Revert unwanted updates

---

package.json
sample/google-contacts.json
src/__snapshots__/transpiler.spec.js.snap
src/transpiler.js

Simple solution to the `Invalid time` bug

fix: Error with birthday when year is undefined

---

src/synchronizeContacts.js

`lodash.without` does not work with objects. Use `filter` to remove from cozy contacts the contacts that have changed on Google side. Also move this outside of the async loops.

Really remove contacts that may produce conflicts

---

package.json
src/CozyUtils.js
src/CozyUtils.spec.js
src/helpers/getAccountId.js
src/onDeleteAccount.js
src/onDeleteAccount.spec.js

Delete trashed contacts related to the account when this account is disconnected

Delete ghosts when account is deleted

---

src/synchronizeContacts.js

More logs for debug (not sure it is a `feat` though (but not a fix or refactor either))

feat: We need more logs here, there and everywhere

---

src/GoogleUtils.js

Or else this could cause some contact update in cozy contact application to be ignored

fix: still request a new syncToken on next page

---

package.json
src/synchronizeContacts.js
webpack.config.js
yarn.lock

Since 95cb0030c3dce6c9513f96d537e6456735846c8c our ci was red.
We fix the issue by installing the babel preset and by adding the babel jest package.

fix: Tests issues
