konnectors/cozy-konnector-google

src/index.js
src/transpiler.js

I would like to stop using `updateOrCreate` but it will be for later, for now I fix the behavior that prevented importing changes from a contact.

fix: unusable ref key

---

README.md

Update README to change the part about `cozy-collect` with doc about how to use the connector with other apps connected to the same stack.
It can be useful when for example we want to test the connector directly from the Cozy Home or to view the descriptions from the manifest in Cozy Store.

doc: Use connector with local apps

---

sample/alanturing.json
sample/google-contacts.json
src/transpiler.js
src/transpiler.spec.js

Google contacts uses the biographies field to store notes about the person. Map this field to cozy `note` field instead of a user defined field (custom).

fix: Map notes field to biographies in google contacts

---

src/index.js

If the Google token does not have the correct scopes (i.e if the token comes from a previous version of the konnector with only readonly scope), we want to throw `USER_ACTION_NEEDED_OAUTH_OUTDATED` instead of `VENDOR_DOWN` error.

feat: throw USER_ACTION_NEEDED_OAUTH_OUTDATED error

---

src/__snapshots__/synchronizeContacts.spec.js.snap
src/__snapshots__/transpiler.spec.js.snap
src/transpiler.js

We were importing this field, but I don't think we  want to keep it? It isn't referenced in any of our working documents.

Fix: Don't import vendor ID

---

src/__snapshots__/transpiler.spec.js.snap
src/transpiler.js
src/transpiler.spec.js

We had an issue with timezones during birthday transpilation. This PR rewrites `getBirthday` and fix this (we just split the ISO date at `T` and take the first part)

fix: Transpile birthday (google to cozy)

---

src/__snapshots__/synchronizeContacts.spec.js.snap
src/google.js
src/index.js
src/synchronizeContacts.js
src/synchronizeContacts.spec.js

Based on https://github.com/konnectors/cozy-konnector-google/pull/252 — deleting a trashed cozy-contact on google (and then on cozy).
Not sure why I needed a snapshot update there though?

Sync delete cozy to google

---

src/__snapshots__/synchronizeContacts.spec.js.snap
src/synchronizeContacts.spec.js

Remove `importedAt` and `importedFrom` occurences to match the "real" `cozyMetadata` structure : [cozy/cozy-doctypes@1e60c85](https://github.com/cozy/cozy-doctypes/commit/1e60c8558b24be3ed3218d20c4414c1db81bd8b4)

Remove importedAt and importedFrom from tests to match the real cozyMetadata

---

src/index.js

We had an issue with this scenario: 
- edit a contact on cozy
- run sync (the contact is updated on google)
- edit the same contact on cozy
- run sync
=> we have the contact both in `cozyContacts` and `googleContacts` so the contact is updated on cozy (instead of google) and we lose the data that we just changed on the contact.
It happened before we use the `syncToken` that we got in response to the google query to retrieve the contacts so the contact(s) we updated on google during sync were in the response of the next query.
This is a simple solution but maybe it should work if we just call `getConnectionsList` (no pagination) with only one field (we would have to revert some of the changes we made yesterday). I'm not sure that it worth it since we just retrieve contacts that we changed …

Ask for a new sync token after sync if we changed something on google side

---

src/__snapshots__/synchronizeContacts.spec.js.snap
src/synchronizeContacts.js
src/synchronizeContacts.spec.js

- Do not crash if a contact deleted on cozy has already been deleted on google
- Don't create contacts that has been deleted on cozy
- Don't even try to delete google contact if no resource name can be found

New fixes on google sync

---

sample/io.cozy.contacts.json
src/__snapshots__/synchronizeContacts.spec.js.snap
src/transpiler.js
src/transpiler.spec.js

People API expect arrays and not strings. Since https://github.com/cozy/cozy-contacts/commit/a2d034eb644c1673762b64642efda459150ca730 transpilation failed.

fix: Transpile empty strings to empty arrays for google

---

src/__snapshots__/synchronizeContacts.spec.js.snap
src/synchronizeContacts.js
src/synchronizeContacts.spec.js

`updateAccountsRelationship` was erasing other relationships

fix: Don't erase other relationships on accounts relationship update

---

src/__snapshots__/synchronizeContacts.spec.js.snap
src/synchronizeContacts.js
src/synchronizeContacts.spec.js

After creating a cozy-contact in google, we didn't init the relationships field.

fix: Init relationships in cozy

---

manifest.konnector
src/CozyUtils.js
src/helpers/getAccountId.js
src/index.js
src/onDeleteAccount.js
webpack.config.js

Set `sourceAccount` to `null` on the `io.cozy.contacts.accounts` when the `io.cozy.accounts` is disconnected
Thus, the Contacts app can know if the account has been disconneted and then don't display the source related to this account.

Set sourceAccount to null on the contact account when the account is deleted

---

src/index.js
src/synchronizeContacts.js

- Fix bug with auth: throw `USER_ACTION_NEEDED_OAUTH_OUTDATED` if we have any `401` or `403` (e.g Invalid credentials) and refresh/retry has failed/is deactivated
- Add more logs
- Avoid total failure if contact is not found on Google

Fix synchronization

---

src/index.js

Since `cozy-konnector-libs` upgrade, the `start` function (`fetch` param of `BaseKonnector`) should take an object (cozy parameters) as second param instead of a boolean (`doRetry`).

fix: start function takes cozyParameters as second param and not doRetry

---

src/index.js

If an error is catched, we should at least throw `VENDOR_DOWN` (there was a case where no error was thrown `Konnector success`)

fix: Never fail silently on auth error

---

src/index.js

`BaseKonnector` now passes 2 params to the `start` function. Thus, `doRetry` should move the third position in params
(Note: we need `doRetry` to avoid infinite retries when google does not respond correctly)

doRetry must be the third parameter of the start function

---

manifest.konnector

We need write permission on accounts to be able to update `accountName`

fix: Allow konnector to update io.cozy.accounts

---

manifest.konnector

`POST` does not seem to work, try `PATCH` instead

fix: Use PATCH instead of POST to allow update on accounts

---

manifest.konnector

Don't use verbs as we still get `Forbidden` errors from the stack.

fix: Do not use verbs, just allow ALL on io.cozy.accounts

---

package.json
src/synchronizeContacts.js
yarn.lock

Use p-limit : https://www.npmjs.com/package/p-limit
The number of concurrent promises is defined by `const limit = pLimit(10)`. Maybe we could put this number in a constant?

Limit number of concurrent promises at the same time

---

src/synchronizeContacts.js

`limit()` takes a function that return a promise or an async function as input. Previously, we passed the result of the execution of the async functions.
This PR also adds more logs for debugging.

fix: Pass async functions to limit() functions

---

src/CozyUtils.js
src/GoogleUtils.js
src/synchronizeContacts.js

- add more logs in `getAllContacts` (google) and `getUpdatedContacts` (cozy) to debug infinite loops or pagination errors
- update promises limit to 50

Add more logs and higher promises limit

---

src/CozyUtils.js
src/CozyUtils.spec.js

Use `limit` and `skip` to query cozy contacts by 100 and avoid infinite queries

fix: Really use pagination on getUpdatedContacts

---

src/__snapshots__/synchronizeContacts.spec.js.snap
src/synchronizeContacts.js
src/synchronizeContacts.spec.js

If `cozyMetadata.sync[contactAccountId].remoteRev` is `undefined` (e.g after a bad migration), search for etag in `metadata.google.metadata.sources.0.etag`. If this one also is undefined, log an error.

Use etag from old metadata if we don't have it in sync, log an error if we have none

---

src/GoogleUtils.js
src/GoogleUtils.spec.js
src/__mocks__/googleapis.js
src/__snapshots__/synchronizeContacts.spec.js.snap
src/synchronizeContacts.js
src/synchronizeContacts.spec.js

Should fix etag error on some instances (first sync after migration), log debug infos if we have the etag problem but don't have 404 error on `getContact`
More details here: https://trello.com/c/RzUwd4MQ/1822-konnector-google-mauvais-etag

Delete contact from cozy if it has been hidden from google

---

.travis.yml
src/__snapshots__/synchronizeContacts.spec.js.snap
src/synchronizeContacts.js
src/synchronizeContacts.spec.js

In case of a disconnect & reconnect, we were pushing updates to Google even though they weren't necessary. Avoiding them gives us more requests before we hit the quota.

fix: Skip useless google updates

---

src/GoogleUtils.js
src/GoogleUtils.spec.js
src/__mocks__/googleapis.js

- if sync token is expired, ask for all contacts without sync token (we don't retrieve deleted contacts in this case)
- I had to rewrite `getConnectionsList` with `async`/`await` to be able to make my unit tests work

fix: Don't use sync token when sync token is expired
